const products = [
  {
    _id: '1',
    name: 'Backpack',
    image: '/images/backpack.jpg',
    description: 'A black fashionable backpack with gold zippers and detail.',
    brand: 'Bag Brand',
    category: 'bags',
    price: '999',
    countInStock: 4,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: '2',
    name: 'Stacked Gold Bracelets',
    image: '/images/bracelets.jpg',
    description: 'Stacked set of three gold bangle bracelets.',
    brand: 'Alena',
    category: 'bracelets',
    price: '499',
    countInStock: 2,
    rating: 4.6,
    numReviews: 9,
  },
  {
    _id: '3',
    name: 'Brown Purse for Women',
    image: '/images/bag.jpg',
    description: 'A brown purse with black jewel detail.',
    brand: 'Bag Brand',
    category: 'bags',
    price: '1399',
    countInStock: 7,
    rating: 4.6,
    numReviews: 29,
  },
  {
    _id: '4',
    name: 'Bright Red Purse With Gold',
    image: '/images/red-purse.jpg',
    description:
      'A delicate red handbag with gold chain strap draped over the top.',
    brand: 'Bag Brand',
    category: 'bags',
    price: '1999',
    countInStock: 9,
    rating: 4.1,
    numReviews: 9,
  },
  {
    _id: '5',
    name: 'Red LED Shoes',
    image: '/images/shoes.jpg',
    description: 'One pair of red high top shoes with blue LED lights.',
    brand: 'Nika',
    category: 'shoes',
    price: '3999',
    countInStock: 18,
    rating: 4.9,
    numReviews: 59,
  },
]

export default products
